new js file
Anastasiia-Sydorchenko/denis_novik pull request #1
Opened 2021-02-02 08:55 UTC by Anastasiia-Sydorchenko

2021-02-02 09:08 UTC, zaharguz requested changes

2021-02-02 09:08 UTC, zaharguz commented on branch-test-file.js
> +   burger.addEventListener('click', () => {
(тестовый ревью) можно добавить пустую строку между объявлением констант и действиями

2021-02-03 06:29 UTC, Anastasiia-Sydorchenko commented on branch-test-file.js
> +   burger.addEventListener('click', () => {
done

2021-02-03 06:30 UTC, zaharguz approved these changes

2021-02-03 06:32 UTC, merged